
CREATE DATABASE RIMACDES
GO
USE RIMACDES
GO
CREATE TABLE PERFIL(
VC_ID_PERFIL VARCHAR(6) NOT NULL PRIMARY KEY,
VC_NOMBRE_PERFIL VARCHAR(50) NOT NULL
)
GO;
CREATE TABLE  USUARIOS(
VC_ID_USUARIO VARCHAR(25) NOT NULL PRIMARY KEY,
VC_NOMBRE VARCHAR(100),
VC_APELLIDO_PATERNO VARCHAR(100),
VC_APELLIDO_MATERNO VARCHAR(100),
VC_EMAIL VARCHAR(100),
VC_PASSWORD VARCHAR(100),
VC_EMPRESA VARCHAR(200),
VC_ID_PERFIL VARCHAR(6)
)
ALTER TABLE USUARIOS ADD CONSTRAINT FK_PERFIL FOREIGN KEY(VC_ID_PERFIL) REFERENCES PERFIL(VC_ID_PERFIL);
GO;
CREATE TABLE INCIDENCIAS(
VC_ID_INCIDENCIA VARCHAR(6) NOT NULL PRIMARY KEY,
VC_TITULO VARCHAR(200),
VC_ID_EMISOR VARCHAR(25),
VC_ID_RECEPTOR VARCHAR(25),
DT_FECHA DATETIME,
VC_DESCRIPCION VARCHAR(200),
VC_ESTADO CHAR(1),  --P=PENDIENTE H=HECHO
VB_VALOR_BINARIO_1 VARBINARY(MAX),
VB_VALOR_BINARIO_2 VARBINARY(MAX),
VB_VALOR_BINARIO_3 VARBINARY(MAX),
VB_VALOR_BINARIO_4 VARBINARY(MAX),
VB_VALOR_BINARIO_5 VARBINARY(MAX)
)
ALTER TABLE INCIDENCIAS ADD CONSTRAINT FK_USUARIO_1 FOREIGN KEY(VC_ID_EMISOR) REFERENCES USUARIOS(VC_ID_USUARIO);
ALTER TABLE INCIDENCIAS ADD CONSTRAINT FK_USUARIO_2 FOREIGN KEY(VC_ID_RECEPTOR) REFERENCES USUARIOS(VC_ID_USUARIO);

--ULTIMO AÑADIDO INCIDENCIA DETALLE 
CREATE TABLE INCIDENCIA_DET(
VC_ID_INCIDENCIA_PREGUNTA VARCHAR(6) NOT NULL,
VC_ID_INCIDENCIA_RESPUESTA VARCHAR(6) NOT NULL,
DT_FECHA_PREGUNTA DATETIME,
DT_FECHA_RESPUESTA DATETIME
)
ALTER TABLE INCIDENCIA_DET ADD CONSTRAINT FK_INCI_1 FOREIGN KEY(VC_ID_INCIDENCIA_PREGUNTA) REFERENCES INCIDENCIAS(VC_ID_INCIDENCIA);
ALTER TABLE INCIDENCIA_DET ADD CONSTRAINT FK_INCI_2 FOREIGN KEY(VC_ID_INCIDENCIA_RESPUESTA) REFERENCES INCIDENCIAS(VC_ID_INCIDENCIA);