
IF OBJECT_ID('RMC_INCIDENCIA_DET') IS NOT NULL
DROP PROC RMC_INCIDENCIA_DET
GO
CREATE PROC RMC_INCIDENCIA_DET
@PCH_TIPO_TRANSACCION CHAR(1), --I=INSERT, S=SELECT,U=UPDATE,D=DELETE
@PVC_ID_INCIDENCIA_PREGUNTA VARCHAR(6) = NULL,
@PVC_ID_INCIDENCIA_RESPUESTA VARCHAR(6) = NULL,
@PDT_FECHA_PREGUNTA DATETIME = NULL,
@PDT_FECHA_RESPUESTA DATETIME = NULL

AS
DECLARE @LVC_SQL NVARCHAR(MAX);
BEGIN
BEGIN  TRY
	IF @PCH_TIPO_TRANSACCION = 'I' --INSERT
	BEGIN
	INSERT INTO INCIDENCIA_DET(VC_ID_INCIDENCIA_PREGUNTA,VC_ID_INCIDENCIA_RESPUESTA,
				DT_FECHA_PREGUNTA,DT_FECHA_RESPUESTA)
	VALUES(@PVC_ID_INCIDENCIA_PREGUNTA,@PVC_ID_INCIDENCIA_RESPUESTA,
				@PDT_FECHA_PREGUNTA,@PDT_FECHA_RESPUESTA)
	END;
ELSE IF @PCH_TIPO_TRANSACCION = 'S' --SELECT
	BEGIN
	SET @LVC_SQL = 'SELECT VC_ID_INCIDENCIA_PREGUNTA,VC_ID_INCIDENCIA_RESPUESTA,
					DT_FECHA_PREGUNTA,DT_FECHA_RESPUESTA FROM INCIDENCIA_DET
					WHERE 1=1 '
	IF @PVC_ID_INCIDENCIA_PREGUNTA IS NOT NULL
	SET @LVC_SQL = @LVC_SQL + ' AND  VC_ID_INCIDENCIA_PREGUNTA = '''+@PVC_ID_INCIDENCIA_PREGUNTA+''' ';
	IF @PVC_ID_INCIDENCIA_RESPUESTA IS NOT NULL
	SET @LVC_SQL = @LVC_SQL + ' AND  VC_ID_INCIDENCIA_RESPUESTA = '''+@PVC_ID_INCIDENCIA_RESPUESTA+'''';
	IF @PDT_FECHA_PREGUNTA IS NOT NULL
	SET @LVC_SQL = @LVC_SQL + ' AND DT_FECHA = '''+ @PDT_FECHA_PREGUNTA + ''' ';
	IF @PDT_FECHA_RESPUESTA IS NOT NULL
	SET @LVC_SQL = @LVC_SQL + ' AND DT_FECHA = '''+ @PDT_FECHA_RESPUESTA + ''' ';
	EXEC (@LVC_SQL);
	END;
END TRY
BEGIN CATCH
	DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;
		SELECT @ErrorMessage = ERROR_MESSAGE(),
			@ErrorSeverity = ERROR_SEVERITY(),
			@ErrorState = ERROR_STATE();
		RAISERROR (@ErrorMessage,@ErrorSeverity,@ErrorState);
END CATCH;
END
