IF OBJECT_ID('RMC_USUARIOS') IS NOT NULL
DROP PROC RMC_USUARIOS
GO
CREATE PROC RMC_USUARIOS
@PCH_TIPO_TRANSACCION CHAR(1), --I=INSERT,S=SELECT,D=DELETE,U=UPDATE
@PVC_ID_USUARIO VARCHAR(25),
@PVC_NOMBRE VARCHAR(100) = NULL,
@PVC_APELLIDO_PATERNO VARCHAR(100) = NULL,
@PVC_APELLIDO_MATERNO VARCHAR(100) = NULL,
@PVC_EMAIL VARCHAR(100) = NULL,
@PVC_PASSWORD VARCHAR(100) = NULL,
@PVC_EMPRESA VARCHAR(200) = NULL,
@PVC_ID_PERFIL VARCHAR(6) = NULL
AS
	BEGIN
		DECLARE @LVC_SQL VARCHAR(2000);

		BEGIN TRY
			IF @PCH_TIPO_TRANSACCION = 'S' --SELECT

			BEGIN
			SET @LVC_SQL = 'SELECT VC_ID_USUARIO,VC_NOMBRE,VC_APELLIDO_PATERNO,VC_APELLIDO_MATERNO,VC_EMAIL,VC_PASSWORD,VC_EMPRESA,VC_ID_PERFIL '
			SET @LVC_SQL = @LVC_SQL + 'FROM USUARIOS '
			IF @PVC_ID_USUARIO IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'WHERE VC_ID_USUARIO = ''' +@PVC_ID_USUARIO+''' ';
			IF @PVC_NOMBRE IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_NOMBRE = '''+@PVC_NOMBRE+''' ';
			IF @PVC_APELLIDO_PATERNO IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_APELLIDO_PATERNO = '''+@PVC_APELLIDO_PATERNO+''' ';
			IF @PVC_APELLIDO_MATERNO IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_APELLIDO_MATERNO = '''+@PVC_APELLIDO_MATERNO+'''';
			IF @PVC_EMAIL IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_EMAIL = '''+@PVC_EMAIL+''' ';
			IF @PVC_PASSWORD IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_PASSWORD = '''+@PVC_PASSWORD+''' ';
			IF @PVC_EMPRESA IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_EMPRESA = '''+@PVC_EMPRESA+''' ';
			IF @PVC_ID_PERFIL IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_ID_PERFIL = '''+@PVC_ID_PERFIL+'''';
		--	PRINT '@LVC_SQL = ' + @LVC_SQL;
			EXEC (@LVC_SQL);
			END;

			ELSE IF  @PCH_TIPO_TRANSACCION = 'I' --INSERT
			BEGIN 
				
				INSERT INTO USUARIOS(VC_ID_USUARIO,VC_NOMBRE,VC_APELLIDO_PATERNO,VC_APELLIDO_MATERNO,VC_EMAIL,
				VC_PASSWORD,VC_EMPRESA,VC_ID_PERFIL)
				VALUES(@PVC_ID_USUARIO,@PVC_NOMBRE,@PVC_APELLIDO_PATERNO,@PVC_APELLIDO_MATERNO,@PVC_EMAIL,
				@PVC_PASSWORD,@PVC_EMPRESA,@PVC_ID_PERFIL);

			END;
			ELSE IF @PCH_TIPO_TRANSACCION = 'U' --UPDATE
			BEGIN
				UPDATE USUARIOS
				SET VC_ID_USUARIO = @PVC_ID_USUARIO,
					VC_NOMBRE = @PVC_NOMBRE,
					VC_APELLIDO_PATERNO = @PVC_APELLIDO_PATERNO,
					VC_APELLIDO_MATERNO = @PVC_APELLIDO_MATERNO,
					VC_EMAIL = @PVC_EMAIL,
					VC_PASSWORD = @PVC_PASSWORD,
					VC_EMPRESA = @PVC_EMPRESA
				WHERE VC_ID_USUARIO = @PVC_ID_USUARIO;
			END;
			ELSE IF @PCH_TIPO_TRANSACCION = 'D' --DELETE
			BEGIN
			DELETE FROM USUARIOS
			WHERE VC_ID_USUARIO = @PVC_ID_USUARIO
			END;
			ELSE IF @PCH_TIPO_TRANSACCION = 'Z' --SELECT PERSONALIZADO
			BEGIN
			SET @LVC_SQL = 'SELECT U.VC_ID_USUARIO,U.VC_NOMBRE+''  ''+U.VC_APELLIDO_PATERNO+'' ''+U.VC_APELLIDO_MATERNO NOMBRE,U.VC_EMAIL,U.VC_EMPRESA,P.VC_NOMBRE_PERFIL '
			SET @LVC_SQL = @LVC_SQL + ' FROM USUARIOS U INNER JOIN PERFIL P ON U.VC_ID_PERFIL = P.VC_ID_PERFIL '
			IF @PVC_ID_USUARIO IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'WHERE VC_ID_USUARIO = ''' +@PVC_ID_USUARIO+''' ';
			IF @PVC_NOMBRE IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_NOMBRE = '''+@PVC_NOMBRE+''' ';
			IF @PVC_APELLIDO_PATERNO IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_APELLIDO_PATERNO = '''+@PVC_APELLIDO_PATERNO+''' ';
			IF @PVC_APELLIDO_MATERNO IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_APELLIDO_MATERNO = '''+@PVC_APELLIDO_MATERNO+'''';
			IF @PVC_EMAIL IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_EMAIL = '''+@PVC_EMAIL+''' ';
			IF @PVC_EMPRESA IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND VC_EMPRESA = '''+@PVC_EMPRESA+''' ';
			IF @PVC_ID_PERFIL IS NOT NULL
				SET @LVC_SQL = @LVC_SQL + 'AND P.VC_ID_PERFIL = '''+@PVC_ID_PERFIL+'''';
		--	PRINT '@LVC_SQL = ' + @LVC_SQL;
			EXEC (@LVC_SQL);
			END;
		END TRY
		BEGIN CATCH
				DECLARE @ErrorMessage NVARCHAR(4000);
				DECLARE @ErrorSeverity INT;
				DECLARE @ErrorState INT; 
				SELECT     @ErrorMessage = ERROR_MESSAGE(),
				@ErrorSeverity = ERROR_SEVERITY(),
				@ErrorState = ERROR_STATE(); 
				RAISERROR (@ErrorMessage, -- Message text.
				   @ErrorSeverity,-- Severity.
				   @ErrorState -- State.
				   ); 
	END CATCH;

	END;



				
			
		
